// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdwojgsrgiihbfjbhtej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkd29qZ3NyZ2lpaGJmamJodGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjMxNzUsImV4cCI6MjA2MzkzOTE3NX0.FX9EVplHbVd4Sm0ljLKvpC8CNKDLvl3D_tcyX_LTZ88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);